### ISSUE TITLE
Server crashes multiple times in combination with ChatControl

### ISSUE THREAD

**Issue by bobhenl** [aBooDyy/LocalTime-Expansion#1]
Hi, when I use Chatcontrol the server is crashing multiple times due to this extension. Author already tried fix it, but there's something wrong with your extension. https://pastebin.com/mNMWh3Zn

**Comment by aBooDyy** [comment]
Hello there,

Thanks for reporting!
I'll look into it and fix it as soon as possible. I will let you know when I do so.

Regards,
aBooDyy

**Comment by aBooDyy** [comment]
Hello again,

I've made a few changes regarding how LocalTime is getting the player's local time. It should fix your issue.
I would like you to test it first and see if it fixes it before pushing the update in the eCloud. It would be great if you can!

You can download the new version from [here](https://aboodyy.net/expansions/LocalTime-Expansion-1.2.jar).
How to install it:
- Go to `/plugins/PlaceholderAPI/expansions` folder.
- Delete the old version of LocalTime expansion.
- Put the new version you downloaded in the folder.
- Reload PlaceholderAPI `/papi reload`.
- And it should work fine. (To be sure, `/papi info LocalTime` and it should tell you its v1.2).

Let me know how it goes with you!

Kind regards,
aBooDyy

**Comment by bobhenl** [comment]
Seems work, hopefully server will stop crash. Thanks for improvements.

**Comment by aBooDyy** [comment]
Glad to hear! Thank you for testing it.
I'll wait for the next week before I update it, just to be sure.
Feel free to contact me if anything went wrong.

Regards,
aBooDyy

**Comment by aBooDyy** [comment]
Hello,

I completely forgot about this 😅 
I've just updated the expansion in the [eCloud](https://api.extendedclip.com/expansions/localtime/versions/localtime-12/) and you can download the latest version now normally by the command.

Thanks again for reporting!

Regards,
aBooDyy
